import time
from playwright.sync_api import sync_playwright

def test_add_note_flow():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        # Use a consistent context to ensure IndexedDB persists if needed, though we are just testing the flow once
        context = browser.new_context()
        page = context.new_page()

        # 1. Navigate to a specific paper page
        # We need a valid ID. Let's use a common one or rely on the mock if we had one.
        # Since this is a live app, we'll try to hit a known paper or the homepage and navigate.
        # However, without a known ID, let's try to search or just go to a hardcoded one if we know it exists.
        # Let's assume the dev server has access to arXiv or is mocking it.
        # If it's hitting real arXiv, '2106.09685' (LoRA) is a good bet.

        print("Navigating to paper page...")
        # We'll use a known paper ID. If fetch fails, the test will fail on content.
        page.goto("http://localhost:4321/paper/2106.09685")

        # Wait for the paper to load
        try:
            page.wait_for_selector("h1", timeout=10000)
        except:
            print("Failed to load paper page. Taking screenshot of error.")
            page.screenshot(path="verification/error_load.png")
            browser.close()
            return

        print("Page loaded. Checking for Notes section...")

        # 2. Check for Notes Section
        # It should say "Notes (0)" initially
        expect_notes_header = page.get_by_text("Notes (0)")
        if expect_notes_header.is_visible():
            print("Notes section found.")
        else:
             print("Notes section NOT found. Taking screenshot.")
             page.screenshot(path="verification/error_no_notes_section.png")
             browser.close()
             return

        # 3. Add a Note
        print("Adding a note...")
        page.get_by_role("button", name="Add Note").click()

        note_content = "This is a test note generated by Playwright."
        page.get_by_placeholder("Type your note here...").fill(note_content)

        # Click the "Add Note" button inside the form (it has the same name)
        # We need to be specific or just pick the second one, or use the container.
        # The form button is the one visible now.
        page.get_by_role("button", name="Add Note").click()

        # 4. Verify Note Added
        print("Verifying note added...")
        # Wait for the note content to appear
        page.wait_for_selector(f"text={note_content}")

        # Check header updated
        if page.get_by_text("Notes (1)").is_visible():
             print("Header updated to Notes (1).")
        else:
             print("Header did not update.")

        # 5. Edit the Note
        print("Editing the note...")
        # Hover over the note card to reveal actions
        note_card = page.locator(".group").first
        note_card.hover()

        # Click Edit
        page.get_by_label("Edit Note").click()

        updated_content = "This is the UPDATED test note."
        page.locator("textarea").fill(updated_content)
        page.get_by_role("button", name="Save").click()

        # Verify update
        page.wait_for_selector(f"text={updated_content}")
        print("Note updated successfully.")

        # 6. Take Screenshot
        print("Taking final screenshot...")
        # Scroll to notes section to ensure it's in view
        page.get_by_text("Notes (1)").scroll_into_view_if_needed()
        time.sleep(0.5) # Allow animations to settle
        page.screenshot(path="verification/verification.png")

        print("Verification complete.")
        browser.close()

if __name__ == "__main__":
    test_add_note_flow()
